In [25]:
import numpy as np
import pandas as pd

Sales_Data=pd.read_csv("https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv")
copy_Sales_Data=Sales_Data.copy()
df=pd.DataFrame(copy_Sales_Data)
print(df.head(5))

   customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No
1  5575-GNVDE    Male              0      No         No      34          Yes
2  3668-QPYBK    Male              0      No         No       2          Yes
3  7795-CFOCW    Male              0      No         No      45           No
4  9237-HQITU  Female              0      No         No       2          Yes

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No
1                No             DSL            Yes  ...              Yes
2                No             DSL            Yes  ...               No
3  No phone service             DSL            Yes  ...              Yes
4                No     Fiber optic             No  ...               No

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes
1          No          No              No        One year               No
2          No          No              No  Month-to-month              Yes
3         Yes          No              No        One year               No
4          No          No              No  Month-to-month              Yes

               PaymentMethod MonthlyCharges  TotalCharges Churn
0           Electronic check          29.85         29.85    No
1               Mailed check          56.95        1889.5    No
2               Mailed check          53.85        108.15   Yes
3  Bank transfer (automatic)          42.30       1840.75    No
4           Electronic check          70.70        151.65   Yes

[5 rows x 21 columns]

In [ ]:
df.drop(['customerID', 'gender','TechSupport', 'InternetService', 'Contract', 'PaymentMethod'], axis=1, inplace=True)
print(df.head(5))

KeyError: "['customerID', 'TechSupport', 'InternetService', 'Contract', 'PaymentMethod'] not found in axis"

In [27]:
df.drop(['OnlineSecurity','Dependents','MultipleLines','DeviceProtection', 'StreamingTV', 'StreamingMovies'], axis=1, inplace=True)
df.head(4)

,SeniorCitizen,Partner,tenure,PhoneService,OnlineBackup,PaperlessBilling,MonthlyCharges,TotalCharges,Churn
0,0,Yes,1,No,Yes,Yes,29.85,29.85,No
1,0,No,34,Yes,No,No,56.95,1889.5,No
2,0,No,2,Yes,Yes,Yes,53.85,108.15,Yes
3,0,No,45,No,No,No,42.30,1840.75,No

In [28]:
df.tail()
df.info()
df.describe()
df.shape
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SeniorCitizen     7043 non-null   int64
 1   Partner           7043 non-null   str
 2   tenure            7043 non-null   int64
 3   PhoneService      7043 non-null   str
 4   OnlineBackup      7043 non-null   str
 5   PaperlessBilling  7043 non-null   str
 6   MonthlyCharges    7043 non-null   float64
 7   TotalCharges      7043 non-null   str
 8   Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(6)
memory usage: 647.7 KB

Index(['SeniorCitizen', 'Partner', 'tenure', 'PhoneService', 'OnlineBackup',
       'PaperlessBilling', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [29]:
df.dtypes

SeniorCitizen         int64
Partner                 str
tenure                int64
PhoneService            str
OnlineBackup            str
PaperlessBilling        str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [30]:
df.loc[0:9]

,SeniorCitizen,Partner,tenure,PhoneService,OnlineBackup,PaperlessBilling,MonthlyCharges,TotalCharges,Churn
0,0,Yes,1,No,Yes,Yes,29.85,29.85,No
1,0,No,34,Yes,No,No,56.95,1889.5,No
2,0,No,2,Yes,Yes,Yes,53.85,108.15,Yes
3,0,No,45,No,No,No,42.30,1840.75,No
4,0,No,2,Yes,No,Yes,70.70,151.65,Yes
5,0,No,8,Yes,No,Yes,99.65,820.5,Yes
6,0,No,22,Yes,Yes,Yes,89.10,1949.4,No
7,0,No,10,No,No,No,29.75,301.9,No
8,0,Yes,28,Yes,No,Yes,104.80,3046.05,Yes
9,0,No,62,Yes,Yes,No,56.15,3487.95,No

In [31]:
df.iloc[0:3]

,SeniorCitizen,Partner,tenure,PhoneService,OnlineBackup,PaperlessBilling,MonthlyCharges,TotalCharges,Churn
0,0,Yes,1,No,Yes,Yes,29.85,29.85,No
1,0,No,34,Yes,No,No,56.95,1889.5,No
2,0,No,2,Yes,Yes,Yes,53.85,108.15,Yes

In [32]:
df.isna().sum()

SeniorCitizen       0
Partner             0
tenure              0
PhoneService        0
OnlineBackup        0
PaperlessBilling    0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [33]:
df.dropna(inplace=True)
df.head(5)

,SeniorCitizen,Partner,tenure,PhoneService,OnlineBackup,PaperlessBilling,MonthlyCharges,TotalCharges,Churn
0,0,Yes,1,No,Yes,Yes,29.85,29.85,No
1,0,No,34,Yes,No,No,56.95,1889.5,No
2,0,No,2,Yes,Yes,Yes,53.85,108.15,Yes
3,0,No,45,No,No,No,42.30,1840.75,No
4,0,No,2,Yes,No,Yes,70.70,151.65,Yes

In [34]:

df['SeniorCitizen'].fillna(5, inplace=True)
df.head(5)

C:\Users\Rana M. Mazhar Khan\AppData\Local\Temp\ipykernel_10064\3478353993.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['SeniorCitizen'].fillna(5, inplace=True)

,SeniorCitizen,Partner,tenure,PhoneService,OnlineBackup,PaperlessBilling,MonthlyCharges,TotalCharges,Churn
0,0,Yes,1,No,Yes,Yes,29.85,29.85,No
1,0,No,34,Yes,No,No,56.95,1889.5,No
2,0,No,2,Yes,Yes,Yes,53.85,108.15,Yes
3,0,No,45,No,No,No,42.30,1840.75,No
4,0,No,2,Yes,No,Yes,70.70,151.65,Yes

In [41]:
grouped = df.groupby('tenure')['MonthlyCharges'].sum()
print(grouped)
summary=df.groupby('tenure').agg(
    MonthlyCharges=('MonthlyCharges', 'max'),
    TotalCharges=('TotalCharges', 'max'))
print(summary)

tenure
0       455.60
1     30947.80
2     13615.10
3     11603.00
4     10108.15
        ...
68     7332.10
69     6728.20
70     9089.10
71    12535.05
72    29211.90
Name: MonthlyCharges, Length: 73, dtype: float64
        MonthlyCharges TotalCharges
tenure
0                80.85
1               102.45        99.75
2               104.40         98.5
3               107.95        99.75
4               105.65        99.95
...                ...          ...
68              118.60      8035.95
69              116.00      8182.85
70              116.55         8250
71              118.65      8564.75
72              118.75       8684.8

[73 rows x 2 columns]

Question 1: Data Structures & Return Types
Consider the following DataFrame initialization:
import pandas as pd
df = pd.DataFrame({"name": ["Ali", "Sara"], "marks": [84, 91]})


(a) What exact data type is returned by type(df["marks"]) versus type(df[["marks"]])?
(b) Under what practical modeling or engineering circumstance is passing double brackets [["marks"]] mandatory?

In [3]:
import pandas as pd
new_df = pd.DataFrame({"name": ["Ali", "Sara"], "marks": [84, 91]})
print(type(new_df["marks"]))
print(type(new_df[["marks"]]))

<class 'pandas.Series'>
<class 'pandas.DataFrame'>

Task 1: Create and Inspect a Series
Create a Pandas Series named exam_scores from the list [88, 92, 79, 95, 68] with custom index labels ["Bio", "Chem", "Physics", "Math", "Eng"]. Print the score for "Physics" using its label, and print the average score across all subjects using the .mean() method.

In [10]:
import pandas as pd
exam_scores =pd.Series([88, 92, 79, 95, 68],index=["Bio", "Chem", "Physics", "Math", "Eng"])
print(exam_scores)
print(exam_scores["Physics"])

Bio        88
Chem       92
Physics    79
Math       95
Eng        68
dtype: int64
79

Task 2: Create a DataFrame from Records & Inspect Types
Create a DataFrame df_students from a list of dictionaries representing 3 students:
records = [
    {"name": "Ali", "age": 22, "marks": 84},
    {"name": "Sara", "age": 21, "marks": 91},
    {"name": "Bilal", "age": 24, "marks": 72}
]

Print the following:
•	1. The type of df_students["marks"] (single bracket)
•	2. The type of df_students[["marks"]] (double brackets)
•	3. The .shape and .dtypes of df_students

In [11]:
records = [
    {"name": "Ali", "age": 22, "marks": 84},
    {"name": "Sara", "age": 21, "marks": 91},
    {"name": "Bilal", "age": 24, "marks": 72}
]
df_students = pd.DataFrame(records)
print(df_students.head(3))
print(type(df_students["marks"]))
print(type(df_students[["marks"]]))
print(df_students.shape)
print(df_students.columns)
print(df_students.dtypes)

    name  age  marks
0    Ali   22     84
1   Sara   21     91
2  Bilal   24     72
<class 'pandas.Series'>
<class 'pandas.DataFrame'>
(3, 3)
Index(['name', 'age', 'marks'], dtype='str')
name       str
age      int64
marks    int64
dtype: object

Task 3: Exploratory Inspection Methods
Using df_students from Task 2, perform the initial exploration steps:
•	1. Print the first 2 rows using .head(2)
•	2. Print summary statistics of the numeric columns using .describe()
•	3. Print the column names using .columns

In [ ]:
print(df_students.head(2))
print(df_students.tail(2))
print(df_students.describe())
print(df_students.columns)

Task 4: Adding, Modifying, and Dropping Columns
Using df_students from Task 2:
•	1. Add a boolean column "passed" indicating whether marks >= 80.
•	2. Add 5 bonus marks to the existing "marks" column in a single vectorized arithmetic line.
•	3. Create a new DataFrame df_no_age by dropping the "age" column without modifying df_students.

In [ ]:
df_students['passed'] = df_students['marks'] >= 80
print(df_students['passed'])
df_students['marks']=df_students['marks']+5
print(df_students['marks'])
df_no_age = df_students.drop('age', axis=1)
print(df_no_age)

Task 5: Compound Boolean Filtering
Given the DataFrame below:
df = pd.DataFrame({
    "name": ["Ali", "Sara", "Ahmed", "Ayesha", "Bilal"],
    "city": ["Lahore", "Karachi", "Lahore", "Islamabad", "Karachi"],
    "marks": [84, 91, 58, 90, 72]
})

Filter and display only the rows where students scored >= 75 AND reside in "Karachi". Make sure each condition is wrapped in parentheses and combined with the bitwise operator &.

In [ ]:
df = pd.DataFrame({
    "name": ["Ali", "Sara", "Ahmed", "Ayesha", "Bilal"],
    "city": ["Lahore", "Karachi", "Lahore", "Islamabad", "Karachi"],
    "marks": [84, 91, 58, 90, 72]
})
print(df.loc[df['marks'] >= 75])

Task 6: Label vs Positional Indexing (.loc vs .iloc)
Using df from Task 5:
•	1. Use .loc[] to slice rows with index labels 1 through 3 and columns "name" and "marks".
•	2. Use .iloc[] to slice the exact same rows and columns by integer position.
•	3. Print both results and observe the inclusive vs. exclusive boundary behavior.

In [ ]:
print(df.loc[1:4, ['name', 'marks']])
print(df.iloc[1:3, [0, 2]])

Task 7: Missing Value Imputation
Create the messy DataFrame below:
df_messy = pd.DataFrame({
    "name": ["Ali", "Sara", "Ahmed", "Ayesha"],
    "age": [22, np.nan, 23, 20],
    "marks": [84, 91, np.nan, 90]
})

•	1. Print the count of missing values per column using .isna().sum().
•	2. Fill missing values in "age" with the mean of "age", and missing values in "marks" with the mean of "marks" in a single .fillna() call using a dictionary.

In [ ]:
import numpy as np
import pandas as pd
df_messy = pd.DataFrame({
    "name": ["Ali", "Sara", "Ahmed", "Ayesha"],
    "age": [22, np.nan, 23, 20],
    "marks": [84, 91, np.nan, 90]
})
print(df_messy.isna().sum())
df_messy['age']=df_messy['age'].fillna(df_messy['age'].mean().round(2), inplace=True)
df_messy['marks']=df_messy['marks'].fillna(df_messy['marks'].mean().round(2), inplace=True)
print(df_messy)

Task 8: String Cleaning with the .str Accessor
Given:
df_dept = pd.DataFrame({
    "employee": ["Ali", "Sara", "Zainab", "Tariq"],
    "department": ["  engineering  ", "Marketing", "ENGINEERING", "sales "]
})

Strip all leading/trailing whitespace and convert the "department" column to title case. Then filter and print all employees belonging to "Engineering".

In [ ]:
df_dept = pd.DataFrame({
    "employee": ["Ali", "Sara", "Zainab", "Tariq"],
    "department": ["  engineering  ", "Marketing", "ENGINEERING", "sales "]
})
df_dept['department'] = df_dept['department'].str.strip().str.lower()
print(df_dept)
print(df_dept['employee'] [df_dept['department'] == 'engineering'])

Task 9: Relational Merge and Missing Keys
Given two DataFrames:
employees = pd.DataFrame({
    "emp_id": [101, 102, 103, 104],
    "name": ["Ali", "Sara", "Ahmed", "Ayesha"],
    "dept_id": ["D1", "D2", "D1", "D99"]
})

departments = pd.DataFrame({
    "dept_id": ["D1", "D2", "D3"],
    "dept_name": ["Engineering", "Marketing", "Finance"]
})

Merge employees and departments on "dept_id" using a left join so that no employee rows are lost. Print the result and note how missing department matches are populated.

In [ ]:
employees = pd.DataFrame({
    "emp_id": [101, 102, 103, 104],
    "name": ["Ali", "Sara", "Ahmed", "Ayesha"],
    "dept_id": ["D1", "D2", "D1", "D99"]
})
departments = pd.DataFrame({
    "dept_id": ["D1", "D2", "D3"],
    "dept_name": ["Engineering", "Marketing", "Finance"]
})
new_df = pd.merge(employees, departments, on='dept_id', how='left')
print(new_df)

Task 10: Concatenation and Deduplication
Given two batches:
batch_1 = pd.DataFrame({"item": ["A", "B", "C"], "price": [10, 20, 30]})
batch_2 = pd.DataFrame({"item": ["B", "D", "E"], "price": [20, 40, 50]})

•	1. Stack the two DataFrames vertically using pd.concat(), passing ignore_index=True to prevent duplicate index labels.
•	2. Identify duplicate items with .duplicated(subset=["item"]) and drop duplicates keeping only the first occurrence via .drop_duplicates().

In [37]:
batch_1 = pd.DataFrame({"item": ["A", "B", "C"], "price": [10, 20, 30]})
batch_2 = pd.DataFrame({"item": ["B", "D", "E"], "price": [20, 40, 50]})

new_batch = pd.concat([batch_1,batch_2], ignore_index=True)
print(new_batch)
print(new_batch.duplicated(subset=["item"]))
print(new_batch.drop_duplicates())

  item  price
0    A     10
1    B     20
2    C     30
3    B     20
4    D     40
5    E     50
0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool
  item  price
0    A     10
1    B     20
2    C     30
4    D     40
5    E     50